### ISSUE TITLE
PulseEffects does not launch since today

### ISSUE THREAD

**Issue by phbn** [flathub/com.github.wwmm.pulseeffects#31] opened 2019-06-23 20:00 UTC
I figure it is probably a new update pushed to flatpak which broke the app. Currently, it does not launch on Linux Mint 19.1.

Tried installing with the PPA, and it launched, however, PulseEffects could not apply effects spite it registering the audio stream.

Can you possibly revert to earlier version which works?

**Comment by wwmm** [comment] 2019-06-23 21:23
It is strange that both packages are having problems. Specially considering that the native Arch Linux package is working.  Sounds like some configuration problem in your PC. Try to do a reset `pulseeffects -r`. If that does not work run the command `pulseeffecs -q` and after that `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Something useful should be printed in the terminal.

**Comment by AsavarTzeth** [comment] 2019-06-23 21:30
I am terribly sorry about this. It was my expectation that this build would still be unpublished.

The breaking change is now reverted: https://github.com/flathub/com.github.wwmm.pulseeffects/commit/383a9584810222352a509f7e2592a0e2d5b7a3d8

Next I will try to find out which version of PulseEffects caused this.

I will leave this open to prevent duplicate issues. Feel free to close it when you have verified it works again.

**Comment by AsavarTzeth** [comment] 2019-06-23 21:34
@wwmm Not sure if it helps but check the commit mentioned in the last comment for my stdout.

I will work on getting you a full debug.

**Comment by AsavarTzeth** [comment] 2019-06-23 21:46
I did a `pulseeffects -r` and `pulseeffects -q`. Here is the full debug output:
https://gist.github.com/AsavarTzeth/dc88e1d9d35d92e519e599ea4a95f800

It's 23:45 here so you are own your own for some time. At least the revert should workaround the immediate problem.

**Comment by wwmm** [comment] 2019-06-23 22:29
Oh! Now I see... The cause of this crash has been fixed in the PE master branch. It is happening because PE could not find pulseaudio executable and the corresponding exception was not being handled. Now I handle it and a crash should not happen. But without pulseaudio exe some of the info about its configuration will not be displayed in PE window.

**Comment by wwmm** [comment] 2019-06-23 22:35
I release PE `4.6.5` with the fix described above. Is it a problem to give access to Pulseaudio executable in flatpak?

**Comment by AsavarTzeth** [comment] 2019-06-24 08:13
Simply granting direct access is indeed a big problem. Security and policies aside it is unlikely to work at all.

- How would you ensure the executable exists at all?
- How can you know where it is located?
- How do you guarantee ABI compatibility or that libraries are available at all? Do you grant access to all host libs too?

If its essential to the app (ex. IDE or terminal emulator) there is a [dbus interface](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml) available that can be used to run commands on the host. Although using it isn't recommended.

Assuming the app is allowed to talk to `org.freedesktop.Flatpak` a quick fix would be to instead run `flatpak-spawn --host pulseaudio` if `/.flatpak-info` exists.

Here is one example of this:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/693/files

**Comment by phbn** [comment] 2019-06-24 08:41
Updated the flatpak this morning. Everything launches and works great! Thanks for the quick response, and the awesome app.

**Closed** 2019-06-24 08:43 UTC

**Comment by wwmm** [comment] 2019-06-24 14:49
The problem is that Pulseaudio does not expose its settings in its API. Only through the output its executable dumps in the terminal we can find output which configs Pulseaudio is really using. I really dislike running system commands but there is no other way in this case =/.

**Comment by AsavarTzeth** [comment] 2019-06-24 14:59
Well in that case there is the path I mentioned earlier. All I would have to do is ensure the app can talk to `org.freedesktop.Flatpak` and I would likely have to test this as well since `flatpak-spawn` is only available inside a Flatpak sandbox.

There is still the question of potential Flathub security policies. As far as I know there is no hard rule against this, but things tend to get stricter with time.

Is this used for anything else than displaying information in the app?

**Comment by wwmm** [comment] 2019-06-24 15:01
No. It is used only in the Pulseaudio information section.

**Comment by wwmm** [comment] 2019-06-24 15:03
THe system call is made here https://github.com/wwmm/pulseeffects/blob/8e95621d6e11a0376b04e12beed7402e942c5db9/src/pulse_info_ui.cpp#L155 and here https://github.com/wwmm/pulseeffects/blob/8e95621d6e11a0376b04e12beed7402e942c5db9/src/pulse_info_ui.cpp#L205
