### ISSUE TITLE
Internal data stream error

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.wwmm.pulseeffects#2] opened 2017-12-27 12:15 UTC
ldconfig: /app/lib/libgfortran.so.3 is not a symbolic link

ldconfig: /app/lib/libquadmath.so.0 is not a symbolic link

(gst-plugin-scanner:4): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstgtk.so': /usr/lib/gstreamer-1.0/libgstgtk.so: undefined symbol: gst_gl_display_wayland_new_with_display
10:00:04.877 - PulseEffects - INFO - pulseaudio context started
10:00:04.883 - PulseEffects - INFO - connected to server: unix:/run/user/1001/pulse/native
10:00:04.890 - PulseEffects - INFO - server protocol version: 32
10:00:04.902 - PulseEffects - INFO - pulseaudio version: 10.0-15-gd4fa3
10:00:04.903 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
10:00:04.903 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
10:00:04.905 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
10:00:04.906 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
10:00:04.909 - PulseEffects - INFO - default pulseaudio source audio format: s16le
10:00:04.910 - PulseEffects - INFO - default pulseaudio source sampling rate: 48000 Hz. We will use the same rate.
10:00:04.910 - PulseEffects - INFO - loading Pulseeffects applications sink...
10:00:05.260 - PulseEffects - INFO - sink owner module index: 25
10:00:05.263 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
10:00:05.264 - PulseEffects - INFO - Pulseeffects apps sink index:1
10:00:05.264 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
10:00:05.264 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
10:00:05.266 - PulseEffects - INFO - sink owner module index: 26
10:00:05.272 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
10:00:05.272 - PulseEffects - INFO - Pulseeffects mic sink index:2
10:00:05.272 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
10:00:05.340 - PulseEffects - INFO - limiter plugin was enabled
10:00:05.341 - PulseEffects - INFO - compressor plugin was enabled
10:00:05.342 - PulseEffects - INFO - highpass plugin was enabled
10:00:05.342 - PulseEffects - INFO - lowpass plugin was enabled
10:00:05.343 - PulseEffects - INFO - equalizer plugin was enabled
10:00:05.344 - PulseEffects - INFO - reverb plugin was enabled
10:00:05.345 - PulseEffects - INFO - spectrum plugin was enabled
10:00:05.491 - PulseEffects - INFO - apps: exciter plugin was enabled
10:00:05.492 - PulseEffects - INFO - apps: bass plugin was enabled
10:00:05.493 - PulseEffects - INFO - apps: stereo plugin was enabled
10:00:05.494 - PulseEffects - INFO - apps: panorama plugin was enabled
10:00:05.494 - PulseEffects - INFO - apps: maximizer plugin was enabled
10:00:05.496 - PulseEffects - INFO - apps: output plugin was enabled
10:00:05.523 - PulseEffects - INFO - limiter plugin was enabled
10:00:05.524 - PulseEffects - INFO - compressor plugin was enabled
10:00:05.525 - PulseEffects - INFO - highpass plugin was enabled
10:00:05.526 - PulseEffects - INFO - lowpass plugin was enabled
10:00:05.527 - PulseEffects - INFO - equalizer plugin was enabled
10:00:05.528 - PulseEffects - INFO - reverb plugin was enabled
10:00:05.528 - PulseEffects - INFO - spectrum plugin was enabled
10:00:27.161 - PulseEffects - INFO - apps: spectrum plugin was enabled
10:00:27.162 - PulseEffects - INFO - mic: spectrum plugin was enabled
10:01:30.268 - PulseEffects - INFO - pipeline state: playing
10:01:30.529 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
10:01:30.530 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
10:01:30.531 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
10:01:30.531 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
10:01:58.221 - PulseEffects - INFO - mic: reverb plugin was enabled
10:02:00.91 - PulseEffects - INFO - mic: reverb plugin was disabled
10:02:14.958 - PulseEffects - INFO - apps: stereo plugin was enabled
10:02:37.246 - PulseEffects - INFO - apps: limiter plugin was enabled

** (pulseeffects:3): CRITICAL **: gst_lv2_filter_setup: assertion 'self->lv2.activated == FALSE' failed

** (pulseeffects:3): CRITICAL **: gst_lv2_filter_setup: assertion 'self->lv2.activated == FALSE' failed
10:02:37.271 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason not-negotiated (-4)')
10:02:37.292 - PulseEffects - INFO - pipeline state: null
10:02:37.310 - PulseEffects - INFO - pipeline state: playing
10:02:37.359 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
10:02:37.361 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
10:02:37.377 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
10:02:37.378 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
10:02:50.228 - PulseEffects - INFO - apps: stereo plugin was disabled
10:02:51.138 - PulseEffects - INFO - apps: stereo plugin was enabled
10:02:56.972 - PulseEffects - INFO - apps: output plugin was enabled
10:02:57.897 - PulseEffects - INFO - apps: output plugin was disabled
10:03:03.897 - PulseEffects - INFO - created stream for sink input 124
10:03:15.904 - PulseEffects - INFO - apps: highpass plugin was enabled
10:03:35.840 - PulseEffects - INFO - apps: equalizer plugin was enabled
10:03:45.489 - PulseEffects - INFO - apps: bass plugin was enabled
10:03:55.241 - PulseEffects - INFO - apps: maximizer plugin was enabled
10:04:06.3 - PulseEffects - INFO - apps: output plugin was enabled
10:04:23.951 - PulseEffects - INFO - apps: compressor plugin was enabled
10:04:47.320 - PulseEffects - INFO - apps: limiter plugin was disabled
10:04:47.336 - PulseEffects - INFO - apps: highpass plugin was disabled
10:04:47.337 - PulseEffects - INFO - apps: compressor plugin was disabled
10:04:47.351 - PulseEffects - INFO - apps: equalizer plugin was disabled
10:04:47.403 - PulseEffects - INFO - apps: bass plugin was disabled
10:04:47.413 - PulseEffects - INFO - apps: stereo plugin was disabled
10:04:47.423 - PulseEffects - INFO - apps: maximizer plugin was disabled
10:04:47.431 - PulseEffects - INFO - apps: output plugin was disabled
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 314, in on_enable_autostart_state_set
    with open(self.autostart_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/com.github.wwmm.pulseeffects/config/autostart/pulseeffects-service.desktop'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 324, in on_enable_autostart_state_set
    os.remove(self.autostart_file)
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/com.github.wwmm.pulseeffects/config/autostart/pulseeffects-service.desktop'
10:05:11.506 - PulseEffects - INFO - created stream for sink input 124
10:05:18.491 - PulseEffects - INFO - pipeline state: null
10:05:18.492 - PulseEffects - INFO - pipeline state: null
10:05:18.499 - PulseEffects - INFO - sinks unloaded
10:05:18.499 - PulseEffects - INFO - disconnecting pulseaudio context
10:05:18.500 - PulseEffects - INFO - pulseaudio context terminated
10:05:18.500 - PulseEffects - INFO - unferencing pulseaudio context object
10:05:18.500 - PulseEffects - INFO - stream for sink input 124 was terminated
10:05:18.500 - PulseEffects - INFO - stopping pulseaudio threaded main loop
10:05:18.505 - PulseEffects - INFO - freeing pulseaudio main loop object

**Comment by wwmm** [comment] 2017-12-27 13:11
I am still trying to understand why lv2 pluguins have the error `CRITICAL **: gst_lv2_filter_setup: assertion 'self->lv2.activated == FALSE' failed` when the limiter plugin is enabled/disabled. It does not happen when other plugins are enabled/disabled. Only the limiter triggers this. In any case there is a workaround in place for that:

```
10:02:37.292 - PulseEffects - INFO - pipeline state: null
10:02:37.310 - PulseEffects - INFO - pipeline state: playing
```  

This puts the pipeline working again. It is not a real solution(probably only gstreamer developers can really fix this) but it is better than closing and opening PulseEffects.

The other error about `FileNotFoundError` is related to the menu feature to auto start the service. I am not sure if this can work in the flatpack package. At least not without it having write permission to the user home. When using standard distribution packages what would happen is the creation of a `pulseeffects-service.desktop` file in the user auto start folder `~/.config/autostart`.

**Comment by LeandroStanger** [comment] 2017-12-27 13:38
@nedrichards Could help

**Comment by AsavarTzeth** [comment] 2018-01-01 23:02
Indeed you cannot autostart applications the traditional way in Flatpak. The reason is that it would compromise the Flatpak security model. If you allowed the application to export a `*.desktop` file it could potentially run whatever command it wants outside the confines of its container.

As for:
```
(gst-plugin-scanner:4): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstgtk.so': /usr/lib/gstreamer-1.0/libgstgtk.so: undefined symbol: gst_gl_display_wayland_new_with_display
```

That might be wayland specific? Are you using wayland? Unfortunately I can not reproduce this on my Intel powered laptop, under the Gnome Wayland Session.

**Comment by nedrichards** [comment] 2018-01-02 18:46
@LeandroStanger won't be on Wayland - he uses Endless OS which is currently a GNOME 3.24 and X11 based system.

**Comment by AsavarTzeth** [comment] 2018-06-12 19:40
Closing for several reasons:

- This issue lacks a clear purpose to begin with. It is just a dump of various unrelated errors and debug information. There is no information as to what should be solved.
- The ldconfig errors have long since been resolved by myself, although they are irrelevant now that gfortran is no longer a dependency.
- PulseEffects has been rewritten in C++ and has generally changed a lot since this was initially opened.

There is one issue still relevant. The fact that PulseEffects the "Start Service at Login" toggle, which in actuality enables autostarting upon login, by writing a desktop entry file to `xdg-config/autostart/`.

That clearly will not work with Flatpak. Ideally a new issue should be opened, focused on this alone, preferably using the upstream bug tracker. I can imagine adding a flatpak/sandbox build option that simply disables this toggle.

**Closed by AsavarTzeth** 2018-06-12 19:40 UTC
