### ISSUE TITLE
Calf from git

### ISSUE THREAD

**Issue by wwmm** [flathub/com.github.wwmm.pulseeffects#12] opened 2018-06-20 21:02 UTC
Calf `0.90.0` has a memory leak in the limiter. I reported it to Calf developers and it was fixed [https://github.com/calf-studio-gear/calf/issues/180](https://github.com/calf-studio-gear/calf/issues/180). But they do not have idea about when there will be a next release. And if I am not mistaken between `0.60` and `0.90` passed 2 and a half years. In Arch Linux anyone who notices the leak have the option of installing `calf-git`. So it is not a big deal. But in flatpak the user can not do something like this.

This is the commit with the fix [https://github.com/calf-studio-gear/calf/commit/7afdefc0d0489a6227fd10f15843d81dc82afd62](https://github.com/calf-studio-gear/calf/commit/7afdefc0d0489a6227fd10f15843d81dc82afd62)

**Comment by AsavarTzeth** [comment] 2018-06-21 08:12
Well in Flatpak its not the user's role to install anything, its mine as the maintainer of all bundled software.

Thanks for the mention. I see that the commit message is "Limiter: try to fix memleak". Is this verified to actually fix the issue?

Also I wonder if changes to this file are minimal since the last release, then maybe I could just back-port a patch instead. No reason to risk other regressions just to fix one issue.

**Comment by wwmm** [comment] 2018-06-21 14:09
Yes. The commit fixes the leak. I installed calf-git here on Arch Linux to test and everything is fine up to now.I also didn't notice any side effect. But I did not test all Calf plugins yet.

In any case I think that just back-porting the fixes should be fine. The function exists in version 0.90 and he only added 3 lines freeing the memory.

**Comment by AsavarTzeth** [comment] 2018-06-28 14:08
Closing since I have pushed a backported patch, which hopefully works.

**Closed by AsavarTzeth** 2018-06-28 14:08 UTC
